### ISSUE TITLE
Deploy stops after a few files

### ISSUE THREAD

**Issue by npateman** [static-publisher/static-publisher#2]
Hi there,

I'm testing static-publisher out on Heroku, deploying to an S3 bucket.  It starts fine, uploads a few documents and then just stops, is there any way of diagnosing what's wrong?

Nick.

**Comment by mushishi78** [comment]
You can have a look at the Heroku logs by using [Heroku CLI](https://devcenter.heroku.com/articles/logging#view-logs).

I imagine if it's stops halfway then there could be some different about the file it stopped at. Perhaps it has a name or file type that S3 doesn't like.

**Comment by npateman** [comment]
Sorry for the delay getting back to you, I ended up using an alternative solution in the end, Travis-CI so don't have any useful information to add to this.  I'll just assume you were correct.  Thanks, I'll close the issue too.
