### ISSUE TITLE
Support for S3 caching headers

### ISSUE THREAD

**Issue by lekkerduidelijk** [static-publisher/static-publisher#3]
Great work @mushishi78 with the static publisher! It's working like a charm.

One thing I was wondering though... Is it possible to add caching headers to the files when they are being uploaded? A `max-age` or `expires` or what so ever would be great.

Do you have any plans to add this in the future? Or maybe you can point me in the right direction.

Cheers

**Comment by mushishi78** [comment]
@lekkerduidelijk I've had a guess at the relevant changes and pushed up to a new feature branch: [cache_control](https://github.com/static-publisher/static-publisher/tree/cache_control). If you could try it out and report back that'd be helpful.

**Comment by lekkerduidelijk** [comment]
Thanks for your quick reply.

I merged your changes into my repo and deployed them. Unfortunately the cache-control header doesn't seem to change after a build...

**Update**
I forgot to update the MongoDB document with the [proper changes](https://github.com/static-publisher/static-publisher/blob/ffed3b71339494277f5f4d26a3e25a1a1b0012d7/config/seed.yml#L4). I'm not sure if that should be form field btw?

I added `"cache_control": "max-age=3600"` to `config.sequences.s3`. (Heroku has a useful web interface via Mongolabs for that)

And it worked! All the files have a max-age of 60 minutes now. :+1: 

A nice to have would be to make a difference between HTML files and assets, but I guess that would require a bit more logic. I use [jekyll-assets](https://github.com/jekyll/jekyll-assets) for cachebusting, so all assets could easily have a max-age of a year.

**Comment by lekkerduidelijk** [comment]
I forgot to properly update the `form.yml`, I see the Cache Control field now.

**Comment by mushishi78** [comment]
Cool. I'll merge into master then.

I don't think there's easy way to differentiate between files without making assumptions, or a complicated UI.

**Comment by lekkerduidelijk** [comment]
You might be right.

I've read this on page speed docs from Google:
https://developers.google.com/speed/docs/insights/LeverageBrowserCaching

They suggest to only do the HTML, consider the rest as long term caching
and use file fingerprints.

The new Amazon Cloudfront compression feature has a list of content-types
they check for.
http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html

Maybe checking on content types and create two configurations, for a short
and long lifetime?
But putting this into an UI could indeed get complicated...

A better idea is to set one default, and create one exception for certain
file extensions. So let's say it defaults to 2 months, and then you set
.html to 1 day?

Just thinking out loud here.

Op do 17 dec. 2015 om 15:07 schreef Max White <notifications@github.com>
